# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
    push:
        branches: [main]
    pull_request: #run tests on all branches
        branches: '*'

jobs:
    quality-tests:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                node-version: [14.x, 18.x]
                os: [ubuntu-latest, windows-latest]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm ci
            - run: npm test

    del_runs:
        runs-on: ubuntu-latest
        steps:
            - name: Delete workflow runs
            - uses: Mattraks/delete-workflow-runs@v2
              with:
                  token: ${{ github.token }}
                  repository: ${{ github.repository }}
                  retain_days: 30
                  keep_minimum_runs: 6

    publish-npm: #publish only main branch
        runs-on: ubuntu-latest
        if: ${{ github.ref == 'refs/heads/main123' }}
        needs: [quality-tests]
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm ci
            - run: npm run semantic-release
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
